development:
  sessions:
    default:
      database: test
      hosts:
        - localhost:27017
  database: test
test:
  sessions:
    default:
      database: test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: app19378148
      hosts:
        - paulo.mongohq.com:10017
      username: heroku
      password: b37d2a8ec2c8f52ff9e8faf3f643ca51
  database: app19378148
